view = createTreeGrid();
viewLoader.setView(view);
view.getMember(0).setData(isc.Tree.create({
	        modelType: "children",
	        nameProperty: "categoryName",
	        childrenProperty: "sub",
				root:{sub:[
					{categoryName:"SSRS Parameter",js:"js/code/ssrs_parameter.js",},
					{categoryName:"First Registration Fee",js:"js/code/first_rec_fee.js",},
					{categoryName:"Fee Code",js:"js/code/fee_code.js",},
					{categoryName:"MMO Ship Type Code",js:"js/code/mmo_ship_type_code.js",},
					{categoryName:"SR Ship Type Code",js:"js/code/ship_type_code.js",},
					{categoryName:"Operation Type",js:"js/code/operation_type.js",},
					{categoryName:"Transaction Code",js:"js/code/trans_code.js",},
					{categoryName:"Reason Code",js:"js/code/reason_code.js",},
					{categoryName:"Mortgage Remark",js:"js/code/mortgage_remark.js",},
					{categoryName:"Class Society",js:"js/code/class_soc.js",},
					{categoryName:"Country Code",js:"js/code/country_code.js",},
					{categoryName:"Port",js:"js/code/port.js",},
					{categoryName:"Group Owner Code",js:"js/code/group_owner_code.js",},
					{categoryName:"Lawyer Information",js:"js/code/lawyer_info.js",},
					{categoryName:"Company Search",js:"js/code/companySearch.js",},
					{categoryName:"Transcript Applicant",js:"js/code/transcriptApplicant.js",},
					{categoryName:"Ship Manager",js:"js/code/ship_manager.js",},
					{categoryName:"Finance Company",js:"js/code/finance_company.js",},
					{categoryName:"Registrar",js:"js/code/registrar.js",},
					{categoryName:"Clinic Code",js:"js/code/clinic_code.js",},
					{categoryName:"English Offensive Word",js:"js/code/eng_offensive_word.js",},
					{categoryName:"Chinese Offensive Word",js:"js/code/chn_offensive_word.js",},
					{categoryName:"Document Remark",js:"js/code/doc_remark.js",},
					{categoryName:"Document Checklist",js:"js/code/doc_checklist.js",},
					{categoryName:"Sea Service Capacity",js:"js/code/mmo_capacity.js",},
					{categoryName:"Seafarer Rank",js:"js/code/mmo_rank.js",},
					{categoryName:"Seafarer Nationality",js:"js/code/mmo_nationality.js",},
					{categoryName:"Seafarer Certificate Name",js:"js/code/mmo_certificate_name.js",},
					{categoryName:"Seafarer Certificate Issuing Authority Name Maintenance",js:"js/code/mmo_certificate_issue_authority_name.js",},
					{categoryName:"Seafarer Training Course",js:"js/code/mmo_training_course.js",},
					{categoryName:"Role",js:"js/code/role.js",},
					{categoryName:"Staff",js:"js/code/staff.js",},
					{categoryName:"Office",js:"js/code/office.js",},
					{categoryName:"User Group",js:"js/code/user_group2.js",},		
				]}}));

