package org.mardep.ssrs.vitaldoc;

import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import migration.Exporter;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:/test-context.xml")
public class TransactionMigration {

	@Autowired
	IVitalDocClient vd;

	/**
	 * read csv generated by readOracle() and write to sqlserver
	 * @throws SQLException
	 * @throws IOException
	 * @throws ClassNotFoundException
	 * @throws InstantiationException
	 * @throws IllegalAccessException
	 * @throws ParseException
	 */
	@Test
	public void read() throws SQLException, IOException, ClassNotFoundException, InstantiationException, IllegalAccessException, ParseException {
		Exporter exporter = new Exporter();
		try {
			exporter.write("com.microsoft.sqlserver.jdbc.SQLServerDriver",
					"jdbc:sqlserver://10.37.115.142:1433;databaseName=SSRS",
					"ssrs_user", "Q1w2e3r4t5");
		} finally {
			exporter.sqlserver.close();
		}
	}

	/**
	 * read ship reg transaction data from oracle and write to csv
	 * @throws SQLException
	 * @throws IOException
	 * @throws ClassNotFoundException
	 * @throws InstantiationException
	 * @throws IllegalAccessException
	 * @throws ParseException
	 */
	@Test
	public void readOracle() throws SQLException, IOException, ClassNotFoundException, InstantiationException, IllegalAccessException, ParseException {
		String driverClass = "oracle.jdbc.driver.OracleDriver";
		String orclUrl = "jdbc:oracle:thin:@10.37.108.131:1521:srisuat";
		String orclUser = "sris";
		String orclPwd = "srissris";

		orclUrl = "jdbc:oracle:thin:@10.37.47.101:1522:srisprod";
		orclPwd = "sris2119";

		new Exporter().readDb(driverClass, orclUrl, orclUser, orclPwd);
	}

}
