/* -- Control table -- start */
IF OBJECT_ID(N'dbo.CONTROL_TABLE', N'U') IS NOT NULL   
DROP TABLE CONTROL_TABLE;  
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTROL_TABLE](
	[ID] [int] IDENTITY NOT NULL,
	[ACTION] [nvarchar](10) NOT NULL,
	[ENTITY] [nvarchar](10) NOT NULL,
	[ENTITY_ID] [nvarchar](19) NOT NULL,
	--[EBS_FLAG] [char](1) NULL,
	[ERROR] [char](1) DEFAULT 0,
	[ERROR_DATE] [datetime2](7) NULL,
	[PROCESSED] [char](1) DEFAULT 0,
	[PROCESSED_DATE] [datetime2](7) NULL,
	[FILE_REQUIRED] [char](1) NULL,
	[FILE] [Varbinary](8000) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[LASTUPD_BY] [nvarchar](50) NULL,
	[LASTUPD_DATE] [datetime2](7) NULL,
	[ROWVERSION] [int] NULL,
 CONSTRAINT [PK_CONTROL_TABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
/* -- Control table -- end */

/* -- SOAP_MESSAGE_OUT -- start */
IF OBJECT_ID(N'dbo.CONTROL_TABLE', N'U') IS NOT NULL   
DROP TABLE SOAP_MESSAGE_OUT;  
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOAP_MESSAGE_OUT](
	[ID] [int] IDENTITY NOT NULL,
	[CONTROL_ID] [int]  NOT NULL,
	[REQUEST] [ntext] NULL,
	[RESPONSE] [ntext] NULL,
	[ERROR] [char](1) NULL,
	[ERROR_DATE] [datetime2](7) NULL,
	[PROCESSED] [char](1) NULL,
	[PROCESSED_DATE] [datetime2](7) NULL,
	[TIMEOUT] [datetime2](7) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[LASTUPD_BY] [nvarchar](50) NULL,
	[LASTUPD_DATE] [datetime2](7) NULL,
	[ROWVERSION] [int] NULL,
 CONSTRAINT [PK_SOAP_MESSAGE_OUT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
/* -- SOAP_MESSAGE_OUT -- end */


/* -- SOAP Message In -- start */
IF OBJECT_ID(N'dbo.SOAP_MESSAGE_IN', N'U') IS NOT NULL   
DROP TABLE SOAP_MESSAGE_IN;  
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOAP_MESSAGE_IN](
	[ID] [int] IDENTITY NOT NULL,
	[REQUEST] [nvarchar](4000) NULL,
	[RESPONSE] [nvarchar](4000) NULL,
	[SENT] [char](1) NULL,
	[SENT_DATE] [datetime2](7) NULL,
	[ERROR] [char](1) NULL,
	[ERROR_DATE] [datetime2](7) NULL,
	[PROCESSED] [char](1) NULL,
	[PROCESSED_DATE] [datetime2](7) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[LASTUPD_BY] [nvarchar](50) NULL,
	[LASTUPD_DATE] [datetime2](7) NULL,
	[ROWVERSION] [int] NULL,
 CONSTRAINT [PK_SOAP_MESSAGE_IN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
/* -- SOAP Message In -- end */
