
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('SHIP_NAME_RESERVATION_READ_ONLY', 		'SHIP NAME RESERVATION READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('SHIP_REGISTRATION_MAINTENANCE_READ_ONLY', 'SHIP REGISTRATION MAINTENANCE READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('AMEND_TRANSACTION_DETAILS_READ_ONLY', 	'AMEND TRANSACTION DETAILS READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('OWNER_ENQUIRY_RECORDS_READ_ONLY', 		'OWNER ENQUIRY RECORDS READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('PRINT_TRANSCRIPT_BATCH_MODE_READ_ONLY', 		'PRINT TRANSCRIPT - BATCH MODE READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);

INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('CSR_FORM_MAINTENANCE_READ_ONLY', 			'CSR FORM MAINTENANCE READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('MAINTAIN_SD_DATA_READ_ONLY', 				'MAINTAIN SD DATA READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);

INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('DEMAND_NOTE_READ_ONLY', 					'DEMAND NOTE READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('DELETE_DEMAND_NOTE_ITEM_READ_ONLY', 		'DELETE DEMAND NOTE ITEM READ_ONLY', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);


INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('FINANCE_REFUND', 		'FINANCE_REFUND', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);


-- for MMO ReadyOnly
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('MMO_REPORT', 						'MMO_REPORT', 					CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('MAINTAIN_SEAFARER_RECORD', 			'MAINTAIN_SEAFARER_RECORD', 	CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('CREW_LIST_OF_AGREEMENT', 			'CREW_LIST_OF_AGREEMENT', 		CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('SHIPLIST_MAINTENANCE', 				'SHIPLIST_MAINTENANCE', 		CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('STOPLIST_MAINTENANCE', 				'STOPLIST_MAINTENANCE', 		CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
INSERT INTO SYSTEM_FUNCS(FUNC_KEY, FUNC_DESC, CREATE_DATE, CREATE_BY, LASTUPD_DATE, LASTUPD_BY, ROWVERSION) values('MMO_ADHOC_DEMAND_NOTE', 			'MMO_ADHOC_DEMAND_NOTE', 		CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 0);
