CREATE TABLE [dbo].[PORTS](
	[CODE] [nvarchar](50) NOT	NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[LASTUPD_BY] [nvarchar](50) NULL,
	[LASTUPD_DATE] [datetime2](7) NULL,
	[ROWVERSION] [int] NULL,
 CONSTRAINT [PK_PORTS] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

